### ISSUE TITLE
Not able to set defaults using new cmds

### ISSUE THREAD

**Issue by mcmiv413** [KevinMarquette/PSGraph#10]
When trying to set a default arrowhead it ignores it if I use the edge command:

This is ignored:
`edge @{arrowhead='none'}`
This works:
`'edge [arrowhead=none]'`

**Comment by KevinMarquette** [comment]
I had a -Default for the node command. I reworked the logic to allow for defaults to be specified more like the DOT notation and removed the -Default.

**Comment by KevinMarquette** [comment]
Resolved with pull request #13 
Published to PSGallery, Release 0.1.7
