### ISSUE TITLE
Additional inline html issues

### ISSUE THREAD

**Issue by mcmiv413** [KevinMarquette/PSGraph#15]
Kevin, thanks for all the updates, a lot of them have worked great, the fix for the inline html worked....partially. If the html is multi line we run into the quote issue again:
```
HTTPS [shape=egg;label=<<TABLE BORDER='0' CELLBORDER='0' CELLSPACING='0'><TR><TD><FONT POINT-SIZE='20'><B><U>HTTPS</U></B></FONT></TD></TR></TABLE>>;]
LoadBalancer [shape=diamond;label="<<TABLE BORDER='0' CELLBORDER='0' CELLSPACING='0'><TR><TD><FONT POINT-SIZE='20'><B><U>LoadBalancer</U></B></FONT></TD></TR>
<TR><TD Align='Center' >10.0.0.0/24</TD></TR></TABLE>";]
```

**Comment by KevinMarquette** [comment]
I relaxed the html detection a bit. I was a bit to strict in my regex. now if the first line contains a table tag, it should use the html syntax. Changes were merged into master with https://github.com/KevinMarquette/PSGraph/pull/16 

Published to PSGallery, release 0.4.1.92
