### ISSUE TITLE
Great Project, One Documentation Nuance

### ISSUE THREAD

**Issue by zloeber** [KevinMarquette/PSGraph#2]
I really like this module, thanks for sharing with the community. One small detail which may be worth throwing up on the main readme.md file is that this is really a DSL powershell wrapper for graphviz (which I suppose is a DSL of its own). As you have constructed it like a DSL it is substantially easier to learn and use than a simple PowerShell module.

In any case, great work, thanks again!

**Comment by KevinMarquette** [comment]
Good feedback. I'll work that in.

**Comment by KevinMarquette** [comment]
https://github.com/KevinMarquette/PSGraph/pull/7
