### ISSUE TITLE
Problems with inline HTML tagging

### ISSUE THREAD

**Issue by mcmiv413** [KevinMarquette/PSGraph#3]
First, thanks for the great module, I used it today to write a script to create a graphviz diagram from an imported CSV.  However there we some issues that I had to work around. When trying to add the inline HTML the module adds quotes around it so the graph has the whole inline HTML in the node instead of rendering off of it. In my script I fixed it by post processing the graph object to replace the "<< and >>"

**Comment by KevinMarquette** [comment]
I have not worked with the HTML syntax much. If I could get a sample of the output you needed, that would help me find a way to handle it.

**Comment by mcmiv413** [comment]
Sure so this:


```
graph basic {
    node a @{label="<TABLE><TR><TD><B><U>Node A</U></B></TD></TR></TABLE>"}
}  
```

Produces:
```
digraph basic {

    "a" [label="<TABLE><TR><TD><B><U>Node A</U></B></TD></TR></TABLE>";]
}
```
The quotes at the beginning and the end of the html need to be <>, it should be producing:
```
digraph basic {

    "a" [label=<<TABLE><TR><TD><B><U>Node A</U></B></TD></TR></TABLE>>;]
}
```

I've been fixing it by post processing the output:
```
$graph = graph basic {
    node a @{label="<TABLE><TR><TD><B><U>Node A</U></B></TD></TR></TABLE>"}
}  
$graph = $graph -replace '"<<','<<'
$graph = $graph -replace '>>"','>>'
$graph 
```

**Comment by KevinMarquette** [comment]
Thank you for the examples. I have some local changes that should resolve this. I do need to rework a bunch of my unit tests before I merge the changes.

**Comment by KevinMarquette** [comment]
I did a lot of refactoring, but I have this working. Resolved in https://github.com/KevinMarquette/PSGraph/pull/12 and deployed to the PSGallery
