### ISSUE TITLE
Not getting "note" type shape 

### ISSUE THREAD

**Issue by larssb** [KevinMarquette/PSGraph#35]
I'm trying to generate a graph that makes use of the "note" type shape. However, I get what seems to be the "oval" shape instead.

- I have tried looking through the code here in the repo to see what could be the culprit, but haven't been able to find it. To be fair I didn't spend hours on that.
- I have read through the DOT language documentation, especially >> http://graphviz.org/content/node-shapes and there I see the "note" shape mentioned. So shouldn't it be available via PSGraph?

> what I want

![image](https://user-images.githubusercontent.com/5261530/28117880-63693756-670f-11e7-965a-263f32c2f543.png)

> what I get

![image](https://user-images.githubusercontent.com/5261530/28117916-82b5e4b0-670f-11e7-8093-e0ff0854f1e8.png)

Is this a bug or am I misunderstanding something?

Thank you 👍

**Comment by KevinMarquette** [comment]
Check your case to make sure it matches the spec. So use `note` instead of `Note`. I have been considering adding logic to resolve this. If everything was lowercase then I would just do a `tolower()` but there are some exceptions.

**Comment by larssb** [comment]
HI @KevinMarquette 

Yup that was it. Simply, the case was the problem. 

Thank you very much. Me not being aware that DOT is case sensitive.
