### ISSUE TITLE
Problems with using multiple array variables in rank

### ISSUE THREAD

**Issue by mcmiv413** [KevinMarquette/PSGraph#4]
Second issue I worked around today is that if you put in arrays to be used by rank in the graph script block you will end up with additional nodes generated with concatenated names. Ie $a = 1,2; $b = 3,4 when used with rank $a,$b will yield nodes (1 2) and (3 4), in my script I add a new variable and add all of the objects into the array then pass it to rank.

**Comment by KevinMarquette** [comment]
Resolved with pull request https://github.com/KevinMarquette/PSGraph/pull/6
