### ISSUE TITLE
Struc syntax not recognized

### ISSUE THREAD

**Issue by mcmiv413** [KevinMarquette/PSGraph#5]
Not sure if this is an issue or I was just doing it wrong, but I was not able to generate a structure using this module, I ended up creating a "dummy" edge and replacing that with the structure syntax after creating the graph object.

**Comment by KevinMarquette** [comment]
Can you give me a sample of a working DOT text showing the structure. I can try to work backward from that.

**Comment by mcmiv413** [comment]
A good example can be found here:

https://www.flickr.com/photos/kentbye/1156412078

```
digraph structs {
node [shape=record];
struct1 [shape=record,label=" left| middle| right"];
struct2 [shape=record,label=" one| two"];
struct3 [shape=record,label="hello\nworld |{ b |{c| d|e}| f}| g | h"];
struct1:f1 -> struct2:f0;
struct1:f2 -> struct3:here;
}
```

I've been using it for embedding images using struct and inline html

**Comment by KevinMarquette** [comment]
I have some local changes that should resolve this. I do need to rework a bunch of my unit tests before I merge the changes.

**Comment by KevinMarquette** [comment]
Resolved in pull request https://github.com/KevinMarquette/PSGraph/pull/12
