### ISSUE TITLE
Support svg as outpu format.

### ISSUE THREAD

**Issue by larssb** [KevinMarquette/PSGraph#71]
The official documentation on Graphviz states that the svg format is an available output option. Could it be possible to make PSGraph support svg?

Thank you and here is a link to the documentation [SVG](https://graphviz.gitlab.io/_pages/doc/info/output.html#d:image_fmts)

**Comment by KevinMarquette** [comment]
I just patched this in. I just needed to update the validate set on the output format. Publishing this now.

**Comment by larssb** [comment]
Nice! It works. I just implemented it in my Out-PSModuleCallGraph. 

Thank you.
