### ISSUE TITLE
Source of  PSGraph/docs/images/networkConnection.png

### ISSUE THREAD

**Issue by LeonardoDG2084** [KevinMarquette/PSGraph#76]
Hi, Could you have the dot source of this example?

PSGraph/docs/images/networkConnection.png

**Comment by Clijsters** [comment]
You can find it [here](https://github.com/KevinMarquette/PSGraph/blob/master/docs/Example-Scripted.md#network-connections):

    $netstat = Get-NetTCPConnection | where LocalAddress -EQ '10.112.11.115'
    
    graph network @{rankdir='LR'}  {
        node @{shape='rect'}
        edge $netstat -FromScript {$_.LocalAddress} -ToScript {$_.RemoteAddress} @{label={'{0}:{1}' -f $_.LocalPort,$_.RemotePort}}
    } | Export-PSGraph -ShowGraph
