### ISSUE TITLE
Version miss match gallery / master branch?

### ISSUE THREAD

**Issue by Stephanevg** [KevinMarquette/PSGraph#87]
I think there is also a problem on the versions between the one available on the gallery, and the one you have on your master branch.

I had the following error: https://github.com/KevinMarquette/PSGraph/issues/85

The fix had been implemented and merged in this PR --> https://github.com/KevinMarquette/PSGraph/issues/78 (the PSD1 indicates version 2.1.30)

The one I downloaded from the gallery using Install-Module Psgraph is version 2.1.33 (Which I couldn't find in any of your psd1 on any of your branches).

It was actually missing a part of that fix:

it has in **Export-PSGraph**: 
```powershell
string[]]
        $GraphVizPath = (
            'C:\Program Files\NuGet\Packages\Graphviz*\dot.exe',
            'C:\program files*\GraphViz*\bin\dot.exe',
            '/usr/local/bin/dot'
        ),
```

instead of:

```powershell
string[]]
        $GraphVizPath = (
            'C:\Program Files\NuGet\Packages\Graphviz*\dot.exe',
            'C:\program files*\GraphViz*\bin\dot.exe',
            '/usr/local/bin/dot',
            '/usr/bin/dot'
        ),
```

which caused me a few issues.

I wanted to apply the fix my self, and PR it, but, It seems already been fixed on your master branch, although on the one I download, it is not the case (and is a higher version then the one on github)

**Comment by KevinMarquette** [comment]
This is corrected now.
