### ISSUE TITLE
Get-Indent error

### ISSUE THREAD

**Issue by mcmiv413** [KevinMarquette/PSGraph#9]
I'm getting the following error when creating a graph:

> Specified argument was out of the range of valid values.
> Parameter name: times
> At C:\Program Files\WindowsPowerShell\Modules\psgraph\0.1.2\private\Get-Indent.ps1:8 char:9
> +         (" " * 4 * $depth )
> +         ~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (:) [], ArgumentOutOfRangeException
>     + FullyQualifiedErrorId : System.ArgumentOutOfRangeException
 
I suspect that the indenting is getting to big because I am nesting graph creations and them plugging the all together afterwards to force positions.

**Comment by KevinMarquette** [comment]
Not exactly sure how you got into this state. I could recreate this error if I could set my index depth to a negative value. I added checks in two places to mitigate this one.
