### ISSUE TITLE
Parse Exception

### ISSUE THREAD

**Issue by TomMaier1** [KevinMarquette/PSGraph#92]
Hi there,

I would like to report the following issue I have experienced.

`
$logMessage = "2019-01-02T15:36:25+00:00 myfqn myuuid OWQ pam_unix(sshd:session): session closed for user mynewuser "

    $groupNames = @('Var1', 'Var2', 'Var3', 'Var4')

    Graph G {
        
        Node -Name "My new Node"
        Node -Name $logMessage

        Edge $groupNames -FromScript { $logMessage } -ToScript { $_ }

    } | Show-PSGraph
}`

Exception message:
`Show-PSGraph : System error.
At C:\myfilepath\myscript.ps1:82 char:9} | Show-PSGraph
         ~~~~~~~~~~~~
    CategoryInfo          : NotSpecified: (:) [Write-Error], ParseException
    FullyQualifiedErrorId : System.Management.Automation.ParseException,Show-PSGraph`

It looks like the colon in the $logMessage variable seems to cause problems.

Can you please look into this?

If you need any further information feel free to message me.

Cheers,
Tom Maier

**Comment by TomMaier1** [comment]
I stumbled across another string that seems to cause a ParseException

"<38>2018-07-23T03:31:27+00:00 hostname sshd[2935]: 'pam_ldap: error trying to bind as user cn=*******,ou=myou,dc=mydc,dc=mydc2,dc=mydc3,dc=mydc4 (Invalid credentials)"

**Comment by TomMaier1** [comment]
Yet another parser exception

Error: Unknown HTML element <UserLogonMethod> on line 1
in label of node message=""Failed\s+(?<UserLogonMethod>.*?)for\s+(?:invalid user)\s+(?<UserAccountNameActing>\S+)\s+from\s+(?<NetworkIPAddressActor>\S+)\s+port\s+(?<NetworkPortActor>\d+).*
Warning: node message=""Failed\s+(?<UserLogonMethod>.*?)for\s+(?, port invalid unrecognized

**Comment by KevinMarquette** [comment]
I'll take a look at these. The colon is a known issue as that is a special character for the graphviz engine that I can't remove support for.

`Set-NodeFormatScript` is supposed to be a workaround, but in testing your example, I can see that it is not working correctly.

There is also some autodetection happening for HTML content that I suspect is causing your second issue.

**Comment by TomMaier1** [comment]
Hi @KevinMarquette,

thanks for your reply. Unfortunately I have to deal with obscurely formatted strings in my PSGraph. I look forward to your solution on this.

Cheers,
Tom

**Comment by KevinMarquette** [comment]
This is confirmed working in `2.1.19` but is broken in `2.1.37`. I need to dig into those releases to see what changed. I thought I had resolved this before.
